### ISSUE TITLE
Scan does not work

### ISSUE THREAD

**Issue by fjsnogueira** [checkmarx-ts/checkmarx-cxflow-github-action#20]
I'm getting the following error, when trying to trigger a sast scan:

2021-04-19 18:50:16.020  INFO 6 --- [           main] c.c.f.CxFlowRunner                        [] : =======BUILD INFO=======
2021-04-19 18:50:16.020  INFO 6 --- [           main] c.c.f.CxFlowRunner                        [] : Version: cx-flow-1.6.19
2021-04-19 18:50:16.021  INFO 6 --- [           main] c.c.f.CxFlowRunner                        [] : Time: 2021-03-18T16:55:30.845Z
2021-04-19 18:50:16.021  INFO 6 --- [           main] c.c.f.CxFlowRunner                        [] : =======================
2021-04-19 18:50:16.744  INFO 6 --- [           main] c.c.f.CxFlowApplication                   [] : Started CxFlowApplication in 7.916 seconds (JVM running for 8.549)
2021-04-19 18:50:16.753  INFO 6 --- [           main] c.c.f.CxFlowRunner                        [r0z8FEad] : Using custom bean implementation  for bug tracking
2021-04-19 18:50:16.804  INFO 6 --- [           main] c.c.f.s.ScaFilterFactory                  [r0z8FEad] : Initializing SCA filters.
2021-04-19 18:50:16.806  INFO 6 --- [           main] c.c.f.CxFlowRunner                        [r0z8FEad] : Executing scan process
2021-04-19 18:50:16.810  INFO 6 --- [           main] c.c.f.s.SastScanner                       [r0z8FEad] : None of the vulnerability scanners is enabled in the configuration. Using CxSAST scanner by default.
2021-04-19 18:50:16.814  INFO 6 --- [           main] c.c.f.s.ProjectNameGenerator              [r0z8FEad] : Project name being used: github-actions-test
2021-04-19 18:50:16.815  INFO 6 --- [           main] c.c.f.u.ZipUtils                          [r0z8FEad] : Creating zip file /github/workspace/cx.8dd51d76-185a-497b-8c1c-6a58afae9439.zip from contents of path .
2021-04-19 18:50:16.839  INFO 6 --- [           main] c.c.f.u.ZipUtils                          [r0z8FEad] : Successfully created /github/workspace/cx.8dd51d76-185a-497b-8c1c-6a58afae9439.zip 
2021-04-19 18:50:16.840  INFO 6 --- [           main] c.c.f.s.ScanRequestConverter              [r0z8FEad] : Overriding team with /***
2021-04-19 18:50:16.860  INFO 6 --- [           main] c.c.s.s.CxAuthService                     [r0z8FEad] : Logging into Checkmarx ***/cxrestapi/auth/identity/connect/token
2021-04-19 18:50:17.410  INFO 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : Retrieving Cx teams
2021-04-19 18:50:17.500  INFO 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : Found team /*** with ID 14
2021-04-19 18:50:17.580  WARN 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : Error occurred while retrieving project with name github-actions-test, http error 403 FORBIDDEN
2021-04-19 18:50:17.582 ERROR 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [no body]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:581)
	at com.checkmarx.sdk.service.CxService.getProjectId(CxService.java:1049)
	at com.checkmarx.flow.sastscanning.ScanRequestConverter.determinePresetAndProjectId(ScanRequestConverter.java:144)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:237)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:278)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:504)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:564)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:504)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:407)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:84)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2021-04-19 18:50:17.583  INFO 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : Creating scan...
2021-04-19 18:50:17.658  WARN 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : Error occurred while retrieving project with name github-actions-test, http error 403 FORBIDDEN
2021-04-19 18:50:17.659 ERROR 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [no body]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:581)
	at com.checkmarx.sdk.service.CxService.getProjectId(CxService.java:1049)
	at com.checkmarx.sdk.service.CxService.determineProjectId(CxService.java:1696)
	at com.checkmarx.sdk.service.CxService.createScan(CxService.java:1603)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:241)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:278)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:504)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:564)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:504)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:407)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:84)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2021-04-19 18:50:17.661  INFO 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : Creating Project github-actions-test for ownerId 14
2021-04-19 18:50:17.762 ERROR 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : HTTP error code 403 FORBIDDEN while creating project with name github-actions-test under owner id 14
2021-04-19 18:50:17.763 ERROR 6 --- [           main] c.c.s.s.CxService                         [r0z8FEad] : org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [no body]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:416)
	at com.checkmarx.sdk.service.CxService.createProject(CxService.java:947)
	at com.checkmarx.sdk.service.CxService.createScan(CxService.java:1606)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:241)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:278)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:504)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:564)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:504)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:407)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:84)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2021-04-19 18:50:17.768 ERROR 6 --- [           main] c.c.f.s.AbstractVulnerabilityScanner      [r0z8FEad] : CheckmarxException: Project was not created successfully: github-actions-test

com.checkmarx.sdk.exception.CheckmarxException: Project was not created successfully: github-actions-test
	at com.checkmarx.sdk.service.CxService.createScan(CxService.java:1608)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:241)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:278)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:504)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:564)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:504)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:407)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:84)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2021-04-19 18:50:17.823  INFO 6 --- [           main] jsonLogger                                [r0z8FEad] : 
2021-04-19 18:50:17.829 ERROR 6 --- [           main] c.c.f.s.AbstractVulnerabilityScanner      [r0z8FEad] : Error occurred

com.checkmarx.flow.exception.MachinaException: Checkmarx Error Occurred: CheckmarxException: Project was not created successfully: github-actions-test
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:256)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:278)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:504)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:564)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:504)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:407)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:84)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2021-04-19 18:50:17.829  INFO 6 --- [           main] c.c.f.CxFlowRunner                        [r0z8FEad] : Finished with exit code: 3
2021-04-19 18:50:17.836  INFO 6 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskExecutor            [] : Shutting down ExecutorService 'webHook'
2021-04-19 18:50:17.837  INFO 6 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskExecutor            [] : Shutting down ExecutorService 'scanRequest'

**Comment by fjsnogueira** [comment]
Hi @MithileshPawar tried with a different project names, and also moved from SAST Scanner all way up to Admin in regards with permissions, nothing changed. Could it be something that was already fixed in some HF? currently I'm running on v9.3 w/o any HF.

**Comment by fjsnogueira** [comment]
Hi @MithileshPawar I've updated checkmarx with the latest HF (HF 4) and still having same issue. Here is my yml file:

`name: CxFlow

on: # Controls when the action will run. Triggers the workflow on pull request events but only for the master branch
#  pull_request:
#    types: [opened, reopened, synchronize] #Types specify which pull request events will trigger the workflow. For more events refer Github Actions documentation.
#    branches:
#      - master      
  push:
    branches:
      - main
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel - this job is specifically configured to use the Checkmarx CxFlow Action
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on - Ubuntu is required as Docker is leveraged for the action
    runs-on: ubuntu-latest
    # Steps require - checkout code, run CxFlow Action, Upload SARIF report (optional)
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout the code
      uses: actions/checkout@v2
    # Runs the Checkmarx Scan leveraging the latest version of CxFlow - REFER to Action README for list of inputs
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
      with:
#        scanners: sast
        project: GithubActionTest
        checkmarx_url: ${{ secrets.CHECKMARX_URL_LOCAL }}
        checkmarx_username: ${{ secrets.CHECKMARX_USERNAME_LOCAL }}
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD_LOCAL }}
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        break_build: false
        team: CxServer #${{ secrets.CHECKMARX_TEAM_LOCAL }} 
`

if I change the version to v1.0-9.x it will work, but that versions is not the latest, and does not support sca scans that I also need.
Can you please show me the simplest possible yml file with v.1.1 that works both for SAST and SCA in checkmarx v9.3 ? because I'm not even able to just use the simplest sample yml to target v1.1. and SAST v9.3.

**Comment by MithileshPawar** [comment]
Hi @fjsnogueira,
You can refer to these samples for the simplest possible configuration to trigger the scans using the action's v1.1.
SAST : https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/blob/master/sample-yml/checkmarx-sast-scan-push.yml
SCA : https://github.com/checkmarx-ts/checkmarx-cxflow-github-action/blob/master/sample-yml/checkmarx-sca-scan-push.yml

These samples are available in the same github action repo. We also have the required documentation if something isn't clear.

To debug your problem, I will suggest starting with individual yml files for SAST and SCA.
Once you have both scans working, the ymls combined into one by just copying the related parameters from both into one.
Kindly note that you need to provide 'sast' and 'sca' as the applicable scanners in the combined yml file as shown below.

e.g-

````
     project: <ProjectName> # <-- Insert Checkmarx SAST Project Name
        team: /CxServer/TeamName
        checkmarx_url: ${{ secrets.CHECKMARX_URL }} # To be stored in GitHub Secrets.
        checkmarx_username: ${{ secrets.CHECKMARX_USER }} # To be stored in GitHub Secrets.
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }} # To be stored in GitHub Secrets.
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }} # To be stored in GitHub Secrets.
        sca_api_url: https://api.scacheckmarx.com
        sca_app_url: https://sca.scacheckmarx.com
        sca_access_control_url: https://platform.checkmarx.net
        sca_tenant: <SCATenant>  # <-- Insert Checkmarx CxSCA Tenant
        sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }} # To be stored in GitHub Secrets.
        sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }} # To be stored in GitHub Secrets.
        break_build: false
        scanners: sast, sca
        bug_tracker: Sarif
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }}  --repo-url="<GitHubRepoUrl>"

````
