### ISSUE TITLE
IllegalArgumentException in URL

### ISSUE THREAD

**Issue by jfivekillerln** [checkmarx-ts/checkmarx-cxflow-github-action#36]
When we are running the action we get this error. 

We have a space in the team name which i think is causing the issue. 

2021-11-18 19:09:30.389 ERROR 6 --- [           main] c.c.f.CxFlowRunner                        [Pezn3DtT] : An error occurred while processing request

java.lang.IllegalArgumentException: Illegal character in path at index 36: ***	/cxwebinterface/Portal/CxWebService.asmx
	at java.net.URI.create(URI.java:852)
	at org.springframework.ws.client.core.WebServiceTemplate$1.getDestination(WebServiceTemplate.java:213)
	at org.springframework.ws.client.core.WebServiceTemplate.getDefaultUri(WebServiceTemplate.java:188)
	at com.checkmarx.sdk.service.CxLegacyService.getDescription(CxLegacyService.java:407)
	at com.checkmarx.sdk.service.CxService.getIssueDescription(CxService.java:922)
	at com.checkmarx.sdk.service.CxService.getIssues(CxService.java:785)
	at com.checkmarx.sdk.service.CxService.getReportContent(CxService.java:443)
	at com.checkmarx.sdk.service.CxService.getReportContentByScanId(CxService.java:374)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.getScanResults(AbstractVulnerabilityScanner.java:146)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:285)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:195)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:558)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:617)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:558)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:435)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:89)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.net.URISyntaxException: Illegal character in path at index 36: ***	/cxwebinterface/Portal/CxWebService.asmx
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)

**Comment by satyamchaurasiapersistent** [comment]
This issue is resolved now. Please raise Salesforce ticket if this issue still persists.
