### ISSUE TITLE
Jira integration

### ISSUE THREAD

**Issue by borecjudo2** [checkmarx-ts/checkmarx-cxflow-github-action#58]
### Version 
`1.5`

### Config

> bug_tracker: JIRA
 jira_url: 'https://***.atlassian.net'
 jira_username: ***
 jira_token: ***
 jira_project: ***
 jira_issue_type: 'Bug'
 jira_open_status: 'In Progress'
 jira_closed_status: 'Done'
 params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }} --jira.priorities.High=High --jira.priorities.Medium=Medium --jira.priorities.Low=Low --jira.priorities.Informational=Lowest

### Issue

> 2022-12-22 18:35:51.519 ERROR 7 --- [           main] c.c.f.CxFlowRunner                        [iVWOox9h] : An error occurred while processing request in commandLineRunner 
java.lang.IllegalArgumentException: No enum constant com.atlassian.jira.rest.client.api.domain.StandardOperation.COPY
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.atlassian.jira.rest.client.api.domain.StandardOperation.valueOf(StandardOperation.java:24)
	at com.atlassian.jira.rest.client.internal.json.CimFieldsInfoJsonParser.parseOperations(CimFieldsInfoJsonParser.java:96)
	at com.atlassian.jira.rest.client.internal.json.CimFieldsInfoJsonParser.parse(CimFieldsInfoJsonParser.java:46)
	at com.atlassian.jira.rest.client.internal.json.CimFieldsInfoMapJsonParser.parse(CimFieldsInfoMapJsonParser.java:54)
	at com.atlassian.jira.rest.client.internal.json.CimIssueTypeJsonParser.parse(CimIssueTypeJsonParser.java:44)
	at com.atlassian.jira.rest.client.internal.json.CimIssueTypeJsonParser.parse(CimIssueTypeJsonParser.java:33)
	at com.atlassian.jira.rest.client.internal.json.GenericJsonArrayParser.parse(GenericJsonArrayParser.java:39)
	at com.atlassian.jira.rest.client.internal.json.GenericJsonArrayParser.parse(GenericJsonArrayParser.java:23)
	at com.atlassian.jira.rest.client.internal.json.CimProjectJsonParser.parse(CimProjectJsonParser.java:47)
	at com.atlassian.jira.rest.client.internal.json.CimProjectJsonParser.parse(CimProjectJsonParser.java:35)
	at com.atlassian.jira.rest.client.internal.json.GenericJsonArrayParser.parse(GenericJsonArrayParser.java:39)
	at com.atlassian.jira.rest.client.internal.json.CreateIssueMetadataJsonParser.parse(CreateIssueMetadataJsonParser.java:34)
	at com.atlassian.jira.rest.client.internal.json.CreateIssueMetadataJsonParser.parse(CreateIssueMetadataJsonParser.java:28)
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$1.handle(AbstractAsynchronousRestClient.java:148)
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$3.apply(AbstractAsynchronousRestClient.java:189)
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$3.apply(AbstractAsynchronousRestClient.java:185)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:57)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:10)
	at io.atlassian.util.concurrent.Promises$OfStage.lambda$fold$4(Promises.java:332)
	at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:422)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.lambda$doCompleted$0(SettableFuturePromiseHttpPromiseAsyncClient.java:37)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:61)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:[114](https://github.com/vertexinc/virus-scanning-service/actions/runs/3760250046/jobs/6390752404#step:5:115)9)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2022-12-22 18:35:51.521  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [iVWOox9h] : Finished with exit code: 10

**Comment by satyamchaurasiapersistent** [comment]
Issue is resolved in latest cx-flow release.
