### ISSUE TITLE
Java Exception Thrown When Running This Action

### ISSUE THREAD

**Issue by JlrekChen** [checkmarx-ts/checkmarx-cxflow-github-action#68]
Case #1: I ran the action in my workflows as below:
# Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@master
      with:
        #project: GithubActionTest
        project: '\CxServer\Ford Enterprise\Information Technology\JAB\jab7'
        team: 'CxServer\Ford Enterprise\Information Technology\JAB'
        checkmarx_url: 'https://www.checkmarx.ford.com'
        checkmarx_username: '${{ secrets.CHECKMARX_USERNAME }}'
        checkmarx_password: '${{ secrets.CHECKMARX_PASSWORD }}'
        checkmarx_client_secret: '${{ secrets.CHECKMARX_CLIENT_SECRET }}'
        preset: 'Ford - Web Services'
        scanners: 'sast'

I got the error:

2023-06-08 20:13:15.220  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [] : Version: cx-flow-1.6.40
2023-06-08 20:13:15.222  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [] : Time: 2023-04-26T11:55:42.189Z
2023-06-08 20:13:15.222  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [] : =======================
2023-06-08 20:13:16.312  INFO 7 --- [           main] c.c.f.CxFlowApplication                   [] : Started CxFlowApplication in 8.071 seconds (JVM running for 8.847)
2023-06-08 20:13:16.325  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [hyAWoemV] : Using custom bean implementation  for bug tracking
2023-06-08 20:13:16.375  INFO 7 --- [           main] c.c.f.s.ScaFilterFactory                  [hyAWoemV] : Initializing SCA filters.
2023-06-08 20:13:16.376  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [hyAWoemV] : Executing scan process
2023-06-08 20:13:16.378  INFO 7 --- [           main] c.c.f.s.ScaFilterFactory                  [hyAWoemV] : Initializing SCA filters.
2023-06-08 20:13:16.383  INFO 7 --- [           main] c.c.f.s.ProjectNameGenerator              [hyAWoemV] : Project name being used: -CxServer-Ford-Enterprise-Information-Technology-JAB-jab7
2023-06-08 20:13:16.385  INFO 7 --- [           main] c.c.f.u.ZipUtils                          [hyAWoemV] : Creating zip file /github/workspace/cx.5cfceca7-3f17-4ca1-b31f-25f8b70fd74d.zip from contents of path .
2023-06-08 20:13:20.624  INFO 7 --- [           main] c.c.f.u.ZipUtils                          [hyAWoemV] : Successfully created /github/workspace/cx.5cfceca7-3f17-4ca1-b31f-25f8b70fd74d.zip 
2023-06-08 20:13:20.625  INFO 7 --- [           main] c.c.f.s.ScanRequestConverter              [hyAWoemV] : Overriding team with /CxServer\Ford Enterprise\Information Technology\JAB
2023-06-08 20:13:20.630  INFO 7 --- [           main] c.c.s.s.CxAuthService                     [hyAWoemV] : Logging into Checkmarx https://www.checkmarx.ford.com/cxrestapi/auth/identity/connect/token
2023-06-08 20:13:21.252  INFO 7 --- [           main] c.c.s.s.CxService                         [hyAWoemV] : Retrieving Cx teams
2023-06-08 20:13:21.342  INFO 7 --- [           main] c.c.s.s.CxService                         [hyAWoemV] : No team was found for /CxServer\Ford Enterprise\Information Technology\JAB
2023-06-08 20:13:21.343  INFO 7 --- [           main] c.c.f.s.ScanRequestConverter              [hyAWoemV] : Existing team with /CxServer\Ford Enterprise\Information Technology\JAB was not found. Creating one ...
2023-06-08 20:13:21.344  INFO 7 --- [           main] c.c.f.s.ScanRequestConverter              [hyAWoemV] : Parent Team: 
2023-06-08 20:13:21.344  INFO 7 --- [           main] c.c.s.s.CxService                         [hyAWoemV] : Retrieving Cx teams
2023-06-08 20:13:21.422  INFO 7 --- [           main] c.c.s.s.CxService                         [hyAWoemV] : No team was found for /CxServer\Ford Enterprise\Information Technology\JAB
2023-06-08 20:13:21.427 ERROR 7 --- [           main] c.c.f.CxFlowRunner                        [hyAWoemV] : An error occurred while processing request in commandLineRunner 

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.parseLong(Long.java:631)
	at com.checkmarx.sdk.service.CxService.createTeam(CxService.java:1828)
	at com.checkmarx.flow.sastscanning.ScanRequestConverter.determineTeamAndOwnerID(ScanRequestConverter.java:102)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:246)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:322)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:201)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanCommon$0(CxFlowRunner.java:626)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:706)
	at com.checkmarx.flow.CxFlowRunner.scanCommon(CxFlowRunner.java:626)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:606)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:482)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:94)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

2023-06-08 20:13:21.428  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [hyAWoemV] : Finished with exit code: 10

Case #2: If I ran the action in my workflows as below:
# Scan code with Checkmarx
    - name: Checkmarx CxFlow Action
      uses: checkmarx-ts/checkmarx-cxflow-github-action@master
      with:
        #project: GithubActionTest
        project: '\CxServer\Ford Enterprise\Information Technology\JAB\jab7'
        team: 'CxServer\Ford Enterprise\Information Technology\JAB'
        checkmarx_url: 'https://www.checkmarx.ford.com'
        checkmarx_username: '${{ secrets.CHECKMARX_USERNAME }}'
        checkmarx_password: '${{ secrets.CHECKMARX_PASSWORD }}'
        checkmarx_client_secret: '${{ secrets.CHECKMARX_CLIENT_SECRET }}'
        preset: 'Ford - Web Services'

I got the error:

2023-06-08 20:16:53.833  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [] : =======================
2023-06-08 20:16:54.811  INFO 7 --- [           main] c.c.f.CxFlowApplication                   [] : Started CxFlowApplication in 8.024 seconds (JVM running for 8.749)
2023-06-08 20:16:54.821  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [KSQdOYkD] : Using custom bean implementation  for bug tracking
2023-06-08 20:16:54.869  INFO 7 --- [           main] c.c.f.s.ScaFilterFactory                  [KSQdOYkD] : Initializing SCA filters.
2023-06-08 20:16:54.871  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [KSQdOYkD] : Executing scan process
2023-06-08 20:16:54.872  INFO 7 --- [           main] c.c.f.s.ScaFilterFactory                  [KSQdOYkD] : Initializing SCA filters.
2023-06-08 20:16:54.876  INFO 7 --- [           main] c.c.f.s.SastScanner                       [KSQdOYkD] : None of the vulnerability scanners is enabled in the configuration. Using CxSAST scanner by default.
2023-06-08 20:16:54.877  INFO 7 --- [           main] c.c.f.s.ProjectNameGenerator              [KSQdOYkD] : Project name being used: -CxServer-Ford-Enterprise-Information-Technology-JAB-jab7
2023-06-08 20:16:54.878  INFO 7 --- [           main] c.c.f.u.ZipUtils                          [KSQdOYkD] : Creating zip file /github/workspace/cx.3c90bcac-06cd-405c-84df-203b1944a6fd.zip from contents of path .
2023-06-08 20:16:59.107  INFO 7 --- [           main] c.c.f.u.ZipUtils                          [KSQdOYkD] : Successfully created /github/workspace/cx.3c90bcac-06cd-405c-84df-203b1944a6fd.zip 
2023-06-08 20:16:59.108  INFO 7 --- [           main] c.c.f.s.ScanRequestConverter              [KSQdOYkD] : Overriding team with \CxServer\Ford Enterprise\Information Technology\JAB
2023-06-08 20:16:59.113  INFO 7 --- [           main] c.c.s.s.CxAuthService                     [KSQdOYkD] : Logging into Checkmarx https://www.checkmarx.ford.com/cxrestapi/auth/identity/connect/token
2023-06-08 20:16:59.747  INFO 7 --- [           main] c.c.s.s.CxService                         [KSQdOYkD] : Retrieving Cx teams
2023-06-08 20:16:59.837  INFO 7 --- [           main] c.c.s.s.CxService                         [KSQdOYkD] : No team was found for \CxServer\Ford Enterprise\Information Technology\JAB
2023-06-08 20:16:59.838  INFO 7 --- [           main] c.c.f.s.ScanRequestConverter              [KSQdOYkD] : Existing team with \CxServer\Ford Enterprise\Information Technology\JAB was not found. Creating one ...
2023-06-08 20:16:59.841 ERROR 7 --- [           main] c.c.f.CxFlowRunner                        [KSQdOYkD] : An error occurred while processing request in commandLineRunner 

java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.util.regex.Pattern.error(Pattern.java:1969)
	at java.util.regex.Pattern.compile(Pattern.java:1708)
	at java.util.regex.Pattern.<init>(Pattern.java:1352)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.split(String.java:2401)
	at java.lang.String.split(String.java:2443)
	at com.checkmarx.flow.sastscanning.ScanRequestConverter.determineTeamAndOwnerID(ScanRequestConverter.java:88)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:246)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:322)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:201)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanCommon$0(CxFlowRunner.java:626)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:706)
	at com.checkmarx.flow.CxFlowRunner.scanCommon(CxFlowRunner.java:626)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:606)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:482)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:94)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:749)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

2023-06-08 20:16:59.842  INFO 7 --- [           main] c.c.f.CxFlowRunner                        [KSQdOYkD] : Finished with exit code: 10

Don't know what causes the error. Maybe there is some bugs in Java program (cx-flow.jar) ?

Case #3: I ran the action in my workflows as below::
# Scan code with SAST Checkmarx
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-github-action@master
      with:
        cxServer: 'https://www.checkmarx.ford.com'
        cxUsername: ${{ secrets.CHECKMARX_USERNAME }}
        cxPassword: ${{ secrets.CHECKMARX_PASSWORD }}
        cxTeam: '\CxServer\Ford Enterprise\Information Technology\JAB'

It was working fine except many "deprecated" warning in the log.

**Comment by rootinfection** [comment]
I'm having this problem too. Even when including the team name the way that's in the documentation get the same result. it happens where or not i use / or \

**Comment by satyamchaurasiapersistent** [comment]
This issue is resolved in latest Cx-flow release. Please raise Salesforce ticket is issue remains persists.
